server:
    interface: 0.0.0.0
    port: 53

    # Разрешаем запросы с самой VM (dns.check.sh делает dig @127.0.0.1)
    access-control: 127.0.0.0/8 allow

    # Разрешаем LAN
    access-control: 192.168.88.0/24 allow

    verbosity: 1

    local-zone: "egor.lan." static
    local-data: "gitea.egor.lan. IN A 192.168.88.234"

forward-zone:
    name: "."
    forward-addr: 8.8.8.8
    forward-addr: 1.1.1.1